version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    # volumes:
    #   - .:/usr/src/app
      #- node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
        # command: "npm start" 
